cli:
  auth_pass: null
  authorize: true
  host: '{{ ansible_host }}'
  password: admin
  username: admin
hostname: os10-LEAF-3
os10_bgp:
  asn: 64626
  best_path:
    as_path: multipath-relax
  graceful_restart: true
  maxpath_ebgp: 2
  neighbor:
  - adv_interval: 1
    fall_over: present
    name: spine-leaf
    timer: 3 9
    type: peergroup
  - address_family:
    - allow_as_in: 1
      type: ipv4
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.1.4
    name: spine-leaf
    peergroup: spine-leaf
    remote_asn: 64600
    timer: 3 9
    type: ipv4
  - address_family:
    - allow_as_in: 1
      type: ipv4
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.2.4
    name: spine-leaf
    peergroup: spine-leaf
    remote_asn: 64600
    timer: 3 9
    type: ipv4
  - admin: up
    ip: 192.168.3.3
    remote_asn: 64626
    type: ipv4
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    ebgp_multihop: 4
    fall_over: present
    ip: 10.0.1.1
    name: spine-leaf
    peergroup: spine-leaf
    remote_asn: 64600
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    src_loopback: 0
    timer: 3 9
    type: ipv4
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    ebgp_multihop: 4
    fall_over: present
    ip: 10.0.1.2
    name: spine-leaf
    peergroup: spine-leaf
    remote_asn: 64600
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    src_loopback: 0
    timer: 3 9
    type: ipv4
  redistribute:
  - address_type: ipv4
    route_map_name: spine-leaf
    route_type: connected
  router_id: 10.0.2.3
os10_interface:
  ethernet 1/1/3:
    admin: up
    desc: Node-02_eth0-NDC1-25G-1
    mtu: 9216
    portmode: trunk
    switchport: true
  ethernet 1/1/10:
    admin: up
    desc: VLT to os10-LEAF-4 1/1/10
    switchport: false
  ethernet 1/1/11:
    admin: up
    desc: VLT to os10-LEAF-4 1/1/11
    switchport: false
  ethernet 1/1/12:
    admin: up
    desc: VLT to os10-LEAF-4 1/1/12
    switchport: false
  ethernet 1/1/13:
    admin: up
  ethernet 1/1/14:
    admin: up
  ethernet 1/1/15:
    admin: up
  ethernet 1/1/2:
    admin: up
  ethernet 1/1/5:
    admin: up
  ethernet 1/1/6:
    admin: up
  ethernet 1/1/4:
    admin: up
    desc: Uplink to os10-SPINE-2 eth1/3
    ip_and_mask: 192.168.2.5/31
    mtu: 9216
    switchport: false
  ethernet 1/1/8:
    admin: up
    desc: Uplink to os10-SPINE-1 eth1/3
    ip_and_mask: 192.168.1.5/31
    mtu: 9216
    switchport: false
  ethernet 1/1/9:
    admin: up
    desc: VLT to os10-LEAF-4 1/1/9
    switchport: false
  loopback 0:
    admin: up
    ip_and_mask: 10.0.2.3/32
  loopback 1:
    admin: up
    ip_and_mask: 1.0.1.2/32
  virtual-network 1010:
    vrf: Vrf1
    ip_and_mask: 172.16.1.3/24
    virtual_gateway_ip: "172.16.1.254"
    admin: up
    desc: "vlan:1010_extended_to_switches:os10-LEAF-1_os10-LEAF-2"
  virtual-network 1020:
    vrf: Vrf1
    ip_and_mask: 172.16.2.3/24
    virtual_gateway_ip: "172.16.2.254"
    admin: up
    desc: "vlan:1020_extended_to_switches:os10-LEAF-1_os10-LEAF-2"
  virtual-network 999:
    vrf: Vrf1
    ip_and_mask: 172.16.0.3/24
    virtual_gateway_ip: "172.16.0.254"
    admin: up
    desc: "vlan:999_extended_to_switches:os10-LEAF-1_os10-LEAF-2"

os10_lldp:
  enable: true
os10_ntp:
  server:
  - ip: 10.204.11.135
    prefer: true
os10_prefix_list:
- entries:
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '16'
    net_num: 10.0.0.0
    number: 10
    permit: true
    state: present
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '16'
    net_num: 1.0.0.0
    number: 20
    permit: true
    state: present
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '16'
    net_num: 192.168.0.0
    number: 30
    permit: true
    state: present
  name: spine-leaf
  state: present
  type: ipv4
os10_route_map:
  route_map:
  - match:
    - ip_type: ipv4
      prefix_list: spine-leaf
    name: spine-leaf
    permit: true
    seq_num: 10
os10_system:
  hostname: os10-LEAF-3
os10_vlan:
  Vlan 1010:
    description: app01
    ip_and_mask: null
    state: present
    tagged_members:
    - port: ethernet 1/1/3
      state: present
  Vlan 1020:
    description: app02
    ip_and_mask: null
    state: present
    tagged_members:
    - port: ethernet 1/1/3
      state: present
  Vlan 4000:
    description: iBGP_link
    ip_and_mask: 192.168.3.2/31
    state: present
  Vlan 999:
    description: cluster01_Management
    ip_and_mask: null
    state: present
    untagged_members:
    - port: ethernet 1/1/3
      state: present
os10_vlt:
  discovery_intf: 1/1/9-1/1/12
  discovery_intf_state: present
  domain: 34
  peer_routing: true
  vlt_mac: 00:00:00:00:00:02
os10_xstp:
  enable: true
  intf:
    ethernet 1/1/3:
      edge_port: true
  rstp:
    bridge_priority: 0
  type: rstp

os10_vrf:
  vrfdetails:
    - vrfname: "Vrf1"
      state: present
